In [1]:
import pandas as pd
from pathlib import Path

local_path = Path('cpi_forecast_selected_variables.csv')
if local_path.exists():
    df = pd.read_csv(local_path)
else:
    url = "https://drive.google.com/uc?id=1SRaVFcphwUBMBJM4WAS-Hx0o-QuGnN0E"
    df = pd.read_csv(url)

df.head()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               360 non-null    str
 1   cpi_mom_inflation  360 non-null    float64
 2   broad_money        360 non-null    float64
 3   ppi_qoq            360 non-null    float64
 4   wti                360 non-null    float64
 5   gold               360 non-null    float64
 6   policy_rate        360 non-null    float64
 7   VNINDEX            360 non-null    float64
 8   NIKKEI225          360 non-null    float64
 9   USDVND             360 non-null    float64
dtypes: float64(9), str(1)
memory usage: 28.3 KB

,cpi_mom_inflation,broad_money,ppi_qoq,wti,gold,policy_rate,VNINDEX,NIKKEI225,USDVND
count,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000
mean,0.020400,5.273617,-0.423583,56.310167,994.854164,7.337222,547.446556,17407.873515,18450.211111
std,0.771484,1.933134,0.651416,28.472136,628.061032,2.788874,390.774063,7116.952347,4246.920358
min,-3.094778,2.617000,-1.660000,11.220000,257.899994,4.000000,101.550000,7568.419922,11004.000000
25%,-0.248855,3.551750,-0.730000,29.002500,313.224998,5.400000,199.505000,11372.137451,15306.000000
50%,0.094397,4.953000,-0.730000,54.510000,1074.400024,6.500000,481.545000,16548.129883,18469.000000
75%,0.383820,6.576000,-0.640000,77.640000,1445.575012,9.000000,895.707500,20695.714844,22701.250000
max,2.419355,10.792000,2.100000,140.000000,2738.300049,15.000000,1498.280000,40369.441406,25480.000000

In [2]:
df.head(50)

,date,cpi_mom_inflation,broad_money,ppi_qoq,wti,gold,policy_rate,VNINDEX,NIKKEI225,USDVND
0,1995-01-01,-0.385356,3.567,-0.73,18.39,278.299988,10.8,101.55,18649.820312,11039.0
1,1995-02-01,-0.385356,3.303,-0.73,18.49,278.299988,10.8,101.55,17053.429688,11050.0
2,1995-03-01,-3.094778,3.495,-0.73,19.17,278.299988,10.8,101.55,16139.950195,11045.0
3,1995-04-01,0.798403,3.434,-0.73,20.38,278.299988,10.8,101.55,16806.750000,11041.0
4,1995-05-01,0.792079,3.247,-0.73,18.89,278.299988,10.8,101.55,15436.790039,11045.0
5,1995-06-01,-0.982318,3.130,-0.73,17.40,278.299988,10.8,101.55,14517.400391,11040.0
6,1995-07-01,-0.793651,3.107,-0.73,17.56,278.299988,10.8,101.55,16677.529297,11030.0
7,1995-08-01,0.300000,3.172,-0.73,17.84,278.299988,10.8,101.55,18117.220703,11025.0
8,1995-09-01,0.199402,2.821,-0.73,17.54,278.299988,10.8,101.55,17913.060547,11015.0
9,1995-10-01,-0.398010,2.889,-0.73,17.64,278.299988,10.8,101.55,17654.640625,11004.0
10,1995-11-01,0.000000,2.844,-0.73,18.18,278.299988,10.8,101.55,18744.419922,11009.0
11,1995-12-01,0.199800,3.072,-0.73,19.55,278.299988,10.8,101.55,19868.150391,11010.0
12,1996-01-01,1.585728,3.100,-0.73,17.74,278.299988,10.8,101.55,20812.740234,11010.0
13,1996-02-01,1.585728,2.924,-0.73,19.54,278.299988,10.8,101.55,20125.369141,11010.0
14,1996-03-01,-1.658537,2.746,-0.73,21.47,278.299988,10.8,101.55,21406.849609,11010.0
15,1996-04-01,-0.694444,2.617,-0.73,21.20,278.299988,10.8,101.55,22041.300781,11010.0
16,1996-05-01,-0.599401,2.720,-0.73,19.76,278.299988,10.8,101.55,21956.189453,11009.0
17,1996-06-01,0.000000,2.833,-0.73,20.92,278.299988,10.8,101.55,22530.750000,11012.0
18,1996-07-01,-0.201005,2.921,-0.73,20.42,278.299988,10.8,101.55,20692.830078,11018.0
19,1996-08-01,0.302115,2.907,-0.73,22.25,278.299988,10.8,101.55,20166.900391,11017.0
20,1996-09-01,0.702811,2.887,-0.73,24.38,278.299988,10.8,101.55,21556.400391,11029.0
21,1996-10-01,-0.199402,3.078,-0.73,23.35,278.299988,10.8,101.55,20466.859375,11060.0
22,1996-11-01,0.799201,3.132,-0.73,23.75,278.299988,10.8,101.55,21020.359375,11089.0
23,1996-12-01,0.099108,2.918,-0.73,25.92,278.299988,10.8,101.55,19361.349609,11146.0
24,1997-01-01,0.992063,2.918,-0.73,24.15,278.299988,10.8,101.55,18330.009766,11177.0
25,1997-02-01,0.992063,2.918,-0.73,20.30,278.299988,10.8,101.55,18557.000000,11201.0
26,1997-03-01,-2.259332,2.739,-0.73,20.41,278.299988,10.8,101.55,18003.400391,11645.0
27,1997-04-01,-0.100503,2.706,-0.73,20.21,278.299988,10.8,101.55,19151.119141,11652.0
28,1997-05-01,0.100604,2.742,-0.73,20.88,278.299988,10.8,101.55,20068.810547,11655.0
29,1997-06-01,0.603015,2.696,-0.73,19.80,278.299988,10.8,101.55,20604.960938,11663.0
30,1997-07-01,0.099900,2.702,-0.73,20.14,278.299988,10.8,101.55,20331.429688,11680.0
31,1997-08-01,-0.099800,2.670,-0.73,19.61,278.299988,10.8,101.55,18229.419922,11694.0
32,1997-09-01,0.499500,2.673,-0.73,21.18,278.299988,10.8,101.55,17887.710938,11715.0
33,1997-10-01,-0.298211,2.893,-0.73,21.08,278.299988,10.8,101.55,16458.939453,12240.0
34,1997-11-01,0.000000,3.057,-0.73,19.15,278.299988,10.8,101.55,16636.259766,12286.0
35,1997-12-01,0.697906,2.892,-0.73,17.64,278.299988,10.8,101.55,15258.740234,12291.0
36,1998-01-01,0.590551,3.034,-0.73,17.21,278.299988,12.0,101.55,16628.470703,12288.0
37,1998-02-01,0.590551,2.983,-0.73,15.44,278.299988,12.0,101.55,16831.669922,12968.0
38,1998-03-01,-2.935421,2.964,-0.73,15.61,278.299988,12.0,101.55,16527.169922,12974.0
39,1998-04-01,2.419355,2.978,-0.73,15.39,278.299988,12.0,101.55,15641.259766,12982.0
40,1998-05-01,-0.196850,2.987,-0.73,15.20,278.299988,12.0,101.55,15670.780273,12982.0
41,1998-06-01,-1.380671,3.033,-0.73,14.18,278.299988,12.0,101.55,15830.269531,12983.0
42,1998-07-01,-0.500000,3.133,-0.73,14.21,278.299988,12.0,101.55,16378.969727,12993.0
43,1998-08-01,1.608040,3.041,-0.73,13.34,278.299988,12.0,101.55,14107.889648,13907.0
44,1998-09-01,-0.098912,3.036,-0.73,16.14,278.299988,12.0,101.55,13406.389648,13900.0
45,1998-10-01,-0.693069,2.987,-0.73,14.42,278.299988,12.0,101.55,13564.509766,13904.0
46,1998-11-01,-0.199402,3.039,-0.73,11.22,278.299988,12.0,101.55,14883.700195,13875.0
47,1998-12-01,0.699301,3.142,-0.73,12.05,278.299988,12.0,101.55,13842.169922,13892.0
48,1999-01-01,0.196657,2.912,-0.73,12.75,278.299988,12.0,101.55,14499.250000,13877.0
49,1999-02-01,0.196657,2.957,-0.73,12.27,278.299988,12.0,101.55,14367.540039,13890.0